### ISSUE TITLE
Quota search sometimes does not work with historical dates

### ISSUE THREAD

**Issue by simonwo** [trade-tariff/trade-tariff-frontend#117]
Hello, your friendly neighbourhood trade data architect from [Department For International Trade](https://github.com/uktrade) here 👋

The quota search sometimes returns garbage when looking at historical dates. For example, this search currently shows the below screenshot for me: https://www.trade-tariff.service.gov.uk/quota_search?order_number=058047&day=15&month=2&year=2021

![image](https://user-images.githubusercontent.com/4951176/122028715-31ef9100-cdc4-11eb-8714-82456c507c6c.png)

The definition popup is mainly blank. The `#-13352` looks like some sort of internal ID as it changes on each refresh of the page.

Let me know if I can help with any more information.

Cheers, 
– Simon

**Comment by simonwo** [comment]
Just an update on this – this specific example seems to have disappeared (maybe due to 7c34655?) but a further issue is 051341: https://www.trade-tariff.service.gov.uk/quota_search?order_number=051341&goods_nomenclature_item_id=&geographical_area_id=&day=15&month=2&year=2021&critical=&status= shows no results for the 15th Feb 2021, but this is in the middle of one of the quota definitions which can be seen here: https://www.trade-tariff.service.gov.uk/commodities/0603150000?day=15&month=2&year=2021

![image](https://user-images.githubusercontent.com/4951176/123442360-b617f480-d5cc-11eb-9617-472ae0894ed8.png)

**Comment by willfish** [comment]
Hi Simon

I'm closing this now as I understand private comms have happened on this and that it's resolved now.

Thanks for communicating this with us

William
